version: '3'

services:
  rabbit-mq:
    build:
      context: ./
      dockerfile: dockers/Dockerfile.RabbitMQ
    restart: always

  postgres:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: app
    image: postgres:latest


  orders-back:
    build:
      context: ./
      dockerfile: dockers/Dockerfile.Backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - rabbit-mq
      - postgres