version: '3'

services:
  rabbit-mq:
    build:
      dockerfile: dockers/Dockerfile.RabbitMQ
    restart: always

  postgres:
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB: app
    image: postgres:latest


  orders-back:
    build:
      dockerfile: dockers/Dockerfile.Backend
    ports:
      - "8080:8080"
    depends_on:
      - rabbit-mq
      - postgres